export const fieldLabels = {
    courseCode: "Mã Khóa Tu",
    secretaryLeaderId: "Thư Kí Phụ Trách",
    courseName: "Tên Khóa Tu",
    startDate: "Ngày Bắt Đầu",
    endDate: "Ngày Kết Thúc",
    expectedStudents: "Số Lượng Khóa Sinh Dự Kiến",
    description: "Mô Tả",
    studentApplicationStartDate: "Ngày Mở Đơn Đăng Ký Học Viên",
    studentApplicationEndDate: "Ngày Kết Thúc Đăng Ký Học Viên",
    volunteerApplicationStartDate: "Ngày Mở Đơn Đăng Ký Tình Nguyện Viên",
    volunteerApplicationEndDate: "Ngày Kết Thúc Đăng Ký Tình Nguyện Viên",
    username: "Tên đăng nhập",
    password: "Mật khẩu",
    fullName: "Họ và Tên",
    dateOfBirth: "Ngày Sinh",
    phoneNumber: "Số Điện Thoại",
    nationalId: "Mã định danh",
    email: "Email",
    gender: "Giới Tính",
    address: "Địa Chỉ",
}

export const button = {
    submit: "Gửi",
    cancel: "Hủy",
    save: "Lưu",
    delete: "Xóa",
    edit: "Sửa",
    view: "Xem",
    create: "Tạo",
    back: "Quay Lại",
    next: "Tiếp Theo",
    previous: "Trước",
    search: "Tìm Kiếm",
    login: "Đăng nhập",
}
